In [2]:
import pandas as pd

perguntas = pd.read_csv("stackoverflow_perguntas.csv")
perguntas.sample(10)

Perguntas                 Tags
2660  Oque é, pra que serve e como funciona o expres...              angular
1761  Estou desenvolvendo uma área onde o aluno se c...               jquery
713   tenho um select2 que é populado do banco de da...  jquery html angular
4016  Criei um CODE  usando o CODE . Funciona da seg...             angular 
4459  Estou utilizando um webService (viaCep) para p...  jquery html angular
696   Como é que posso remover uma linha de uma tabe...                 html
3303  Queria saber como eu faço para concatenar um l...                 html
4865  Estou desenvolvendo uma mini loja. Gostaria de...                html 
55    Quais a melhores ferramentas para serem utiliz...              node.js
573   Estou armazenando alguns dados no localstorage...                 html

In [3]:
print(len(perguntas))

5408


In [4]:
perguntas.Tags.unique()

array(['node.js', 'jquery', 'html', 'html angular ', 'html ', 'angular',
       'angular ', 'jquery html  ', 'jquery ', 'jquery html',
       'jquery html ', 'html angular', 'angular node.js ', 'html  ',
       'jquery html angular', 'node.js ', 'html jquery', 'html jquery ',
       'jquery angular  ', 'html node.js', 'jquery  ', 'angular node.js',
       'jquery angular', 'html node.js ', 'jquery node.js ', 'angular  ',
       'jquery angular ', 'jquery html angular ', 'node.js html ',
       ' node.js', 'node.js html', 'html angular  ', 'jquery node.js',
       'angular html', 'html angular  node.js', 'jquery html node.js',
       'html angular node.js'], dtype=object)

In [5]:
lista_de_tags = list()
for tags in perguntas.Tags.unique():
    for tag in tags.split():
        if tag not in lista_de_tags:
            lista_de_tags.append(tag)
        
print(lista_de_tags)

['node.js', 'jquery', 'html', 'angular']


In [6]:
node_js = list()
for linha_tag in perguntas.Tags:
    if "node.js" in linha_tag:
        node_js.append(1)
    else:
        node_js.append(0)
perguntas["node.js"] = node_js
perguntas

Perguntas           Tags  node.js
0     Possuo um projeto Node.js porém preciso criar ...        node.js        1
1     Gostaria de fazer testes unitários no Node.js,...        node.js        1
2     Como inverter a ordem com que o jQuery itera u...         jquery        0
3     Eu tenho uma página onde pretendo utilizar um ...           html        0
4     Como exibir os dados retornados do FireStore e...  html angular         0
...                                                 ...            ...      ...
5403  Queria saber como pegar o total de cores de um...   jquery html         0
5404  Boa noite, estou usando phonegap para fazer um...          html         0
5405  Estou construindo um mini fórum, e nele, os us...    jquery html        0
5406  Boa tarde,  Estou para desenvolver um site na ...           html        0
5407  Estou fazendo um hotsite, ele é one page, e é ...    jquery html        0

[5408 rows x 3 columns]

In [7]:
def nova_coluna(lista_tags, dataframe, nome_tags):
    for tag in lista_tags:
        coluna = list()
        for linha_tag in dataframe[nome_tags]:
            if tag in linha_tag:
                coluna.append(1)
            else:
                coluna.append(0)
        dataframe[tag] = coluna
nova_coluna(lista_de_tags, perguntas, "Tags")
perguntas.sample(10)

Perguntas  ... angular
3845  Na função success não estou conseguindo setar ...  ...       0
2620  Galera teria como por meio de algum javascript...  ...       0
2190  Estou a fazer a seguinte operação:  Pego o tex...  ...       1
1474  Estou começando a realizar projetos com o node...  ...       0
1289  Tentei vários tutoriais na internet antes de v...  ...       0
5393  Tenho um script em CODE  que pega o CODE  de u...  ...       0
1882  Estou tentando ler um arquivo .txt de 3.5GB li...  ...       0
4377  Estou com um dúvida sobre como um servidor nod...  ...       0
1201  Defini diversos DataAnnotations para o modelo ...  ...       0
4175  Olá,  Podem me dizer por favor onde está o err...  ...       0

[10 rows x 6 columns]

In [9]:

from sklearn.model_selection import train_test_split

perguntas_treino, perguntas_test, tags_treino, tags_teste = train_test_split(
    perguntas.Peguntas,
    perguntas.Tags
)

AttributeError: ignored

In [10]:
lista_1 = [1,2]
lista_2 = [5,4]
lista_zip = zip(lista_1, lista_2)
print(list(lista_zip))

[(1, 5), (2, 4)]


In [11]:
lista_zip_tags = list(zip(perguntas[lista_de_tags[0]],
                     perguntas[lista_de_tags[1]],
                     perguntas[lista_de_tags[2]],
                     perguntas[lista_de_tags[3]]))

perguntas["todas_tags"] = lista_zip_tags
perguntas.sample(10)

Perguntas  ...    todas_tags
2982  Ao clicar em um botão, preciso que carregue mi...  ...  (0, 1, 0, 0)
4231  Tenho um gráfico que é criado conforme o ano, ...  ...  (0, 1, 0, 0)
2830  A ideia é fazer com que ao chamar uma diretiva...  ...  (0, 0, 0, 1)
1455  Como faço para importar esse DASHBOARD feito e...  ...  (0, 0, 1, 0)
1260  Atualmente estou utilizando ajax fazendo vária...  ...  (0, 1, 0, 0)
4405  Olá!  Eu criei um aplicativo em HTML5 + JQuery...  ...  (0, 0, 1, 0)
1771  Tenho meus elementos  em um texto.  CODE   e e...  ...  (0, 0, 1, 0)
1650  usei muito javascript/jquery para montar um pr...  ...  (0, 1, 0, 0)
5397  Preciso pegar a data atual e somar dias de aco...  ...  (0, 0, 1, 0)
4612  Eu estou tentando desabilitar um modal do boot...  ...  (0, 0, 1, 0)

[10 rows x 7 columns]

In [12]:
lista_de_tags

['node.js', 'jquery', 'html', 'angular']

In [13]:
from sklearn.model_selection import train_test_split

perguntas_treino, perguntas_test, tags_treino, tags_teste = train_test_split(
    perguntas.Perguntas,
    perguntas.todas_tags,
    test_size = 0.2,
    random_state = 123
)

In [14]:
perguntas_treino

1577       array1 = [1,2,3];   array2 = ["um","dois","...
1927    Não sei se fui claro no título, mas quem é da ...
3409    Alguém sabe me dizer qual a melhor forma de re...
4606    Estou com problemas ao tentar validar campos d...
5237    Preciso copiar um valor de dentro de um CODE  ...
                              ...                        
5218    Tenho um sisteminha, para mudar o layout da pá...
4060    Como fazer alto scoll ao carregar a página?  E...
1346    Explicação:  Tenho uma CODE  pai que contém du...
3454    Estou querendo fazer um sistema onde eu iria t...
3582    Galera eu to com um problemão, ja pesquisei ba...
Name: Perguntas, Length: 4326, dtype: object

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

vetorizar = TfidfVectorizer(max_features=5000, max_df=0.85)
vetorizar

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=0.85, max_features=5000,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [16]:
vetorizar.fit(perguntas.Perguntas)
perguntas_treino_tfidf = vetorizar.transform(perguntas_treino)
perguntas_test_tfidf = vetorizar.transform(perguntas_test)
print(perguntas_treino_tfidf.shape)
print(perguntas_test_tfidf.shape)

(4326, 5000)
(1082, 5000)


In [18]:
import numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_test_array = np.asarray(list(tags_teste))

In [19]:
tags_treino_array

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       ...,
       [0, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 0]])

In [20]:
type(tags_treino)

pandas.core.series.Series

In [22]:
type(tags_treino)

pandas.core.series.Series

In [23]:
import numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_teste_array = np.asarray(list(tags_teste))
print(tags_treino_array)
print(type(tags_treino_array))

[[0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 ...
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]]
<class 'numpy.ndarray'>


In [24]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression(solver = 'lbfgs')
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_onevsrest = classificador_onevsrest.score(perguntas_test_tfidf, tags_teste_array)
print("Resultado {0: .2f}%".format(resultado_onevsrest*100))

Resultado  41.68%


In [25]:
perguntas.todas_tags.unique()

array([(1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 1, 1),
       (0, 0, 0, 1), (0, 1, 1, 0), (1, 0, 0, 1), (0, 1, 1, 1),
       (0, 1, 0, 1), (1, 0, 1, 0), (1, 1, 0, 0), (1, 0, 1, 1),
       (1, 1, 1, 0)], dtype=object)

In [26]:
len(perguntas.todas_tags.unique())

13

In [27]:
1/13

0.07692307692307693

In [28]:
from sklearn.metrics import hamming_loss

previsao_onevsrest = classificador_onevsrest.predict(perguntas_test_tfidf)
hamming_loss_onevsrest = hamming_loss(tags_teste_array, previsao_onevsrest)
print("Hamming Loss {0: .2f}".format(hamming_loss_onevsrest))

Hamming Loss  0.19


In [29]:
perguntas.corr()

node.js    jquery      html   angular
node.js  1.000000 -0.321485 -0.273523 -0.101787
jquery  -0.321485  1.000000 -0.253977 -0.366269
html    -0.273523 -0.253977  1.000000 -0.286706
angular -0.101787 -0.366269 -0.286706  1.000000

In [30]:
!pip install scikit-multilearn

     |████████████████████████████████| 89 kB 3.3 MB/s 


In [31]:
from skmultilearn.problem_transform import ClassifierChain

classificador_cadeia = ClassifierChain(regressao_logistica)
classificador_cadeia.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_cadeia = classificador_cadeia.score(perguntas_test_tfidf, tags_teste_array)
previsao_cadeia = classificador_cadeia.predict(perguntas_test_tfidf)
hamming_loss_cadeia = hamming_loss(tags_teste_array, previsao_cadeia)
print("Hamming Loss {0: .2f}".format(hamming_loss_cadeia))
print("Resultado {0: .2f}%".format(resultado_cadeia*100))

Hamming Loss  0.21
Resultado  49.82%


In [32]:
from skmultilearn.problem_transform import BinaryRelevance

classificador_br = BinaryRelevance(regressao_logistica)
classificador_br.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_br = classificador_br.score(perguntas_test_tfidf, tags_teste_array)
previsao_br = classificador_br.predict(perguntas_test_tfidf)
hamming_loss_br = hamming_loss(tags_teste_array, previsao_br)
print("Hamming Loss {0: .2f}".format(hamming_loss_br))
print("Resultado {0: .2f}%".format(resultado_br*100))

Hamming Loss  0.19
Resultado  41.68%


In [33]:
from skmultilearn.adapt import MLkNN

classificador_mlknn = MLkNN()

classificador_mlknn.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_mlknn = classificador_mlknn.score(perguntas_test_tfidf, tags_teste_array)
previsao_mlknn = classificador_mlknn.predict(perguntas_test_tfidf)
hamming_loss_mlknn = hamming_loss(tags_teste_array, previsao_mlknn)
print("Hamming Loss {0: .2f}".format(hamming_loss_mlknn))
print("Resultado {0: .2f}%".format(resultado_mlknn*100))

Hamming Loss  0.25
Resultado  32.53%
